services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  Tourze\TencentMeetingBundle\Controller\:
    resource: '../../Controller/'
    public: true
  Tourze\TencentMeetingBundle\Factory\:
    resource: '../../Factory/'
    public: true
  Tourze\TencentMeetingBundle\Repository\:
    resource: '../../Repository/'
  Tourze\TencentMeetingBundle\Service\:
    resource: '../../Service/'
    public: true
